MaxRanks = {
        ['galaxycity'] = 2,
        ['police'] = 17,
        ['ambulance'] = 12,
		    ['fib'] = 12,
        ['cali'] = 11,
        ['mechanic'] = 6,
        ['goodfellas'] = 5,
        ['greymarkt'] = 6,
        ['merryweather'] = 2,
        ['mg13'] = 12,
        ['firefighter'] = 2,
        ['goldenpub'] = 2,
    },
